In [1]:
import os
import pandas as pd

In [2]:
df = pd.read_csv("../../data/response/Fire_Incident_Dispatch_Data.csv")
is_valid_rspns_time = df['VALID_INCIDENT_RSPNS_TIME_INDC'] == 'Y'
valid_rspns_times = df[is_valid_rspns_time]

In [3]:
valid_rspns_times.shape

(2757412, 29)

In [4]:
sorted = valid_rspns_times.sort_values(by=['INCIDENT_TRAVEL_TM_SECONDS_QY'], ascending=False)
print(sorted['INCIDENT_TRAVEL_TM_SECONDS_QY'].quantile(.05))
print(sorted['INCIDENT_TRAVEL_TM_SECONDS_QY'].quantile(.95))

130.0
480.0

In [5]:
sorted

,STARFIRE_INCIDENT_ID,INCIDENT_DATETIME,ALARM_BOX_BOROUGH,ALARM_BOX_NUMBER,ALARM_BOX_LOCATION,INCIDENT_BOROUGH,ZIPCODE,POLICEPRECINCT,CITYCOUNCILDISTRICT,COMMUNITYDISTRICT,...,FIRST_ACTIVATION_DATETIME,FIRST_ON_SCENE_DATETIME,INCIDENT_CLOSE_DATETIME,VALID_DISPATCH_RSPNS_TIME_INDC,VALID_INCIDENT_RSPNS_TIME_INDC,INCIDENT_RESPONSE_SECONDS_QY,INCIDENT_TRAVEL_TM_SECONDS_QY,ENGINES_ASSIGNED_QUANTITY,LADDERS_ASSIGNED_QUANTITY,OTHER_UNITS_ASSIGNED_QUANTITY
868409,1.721326e+15,08/01/2017 10:57:22 PM,BROOKLYN,2584,12 AVE & 43 ST,BROOKLYN,NaN,NaN,NaN,NaN,...,08/01/2017 10:57:54 PM,08/01/2017 11:57:09 PM,08/01/2017 11:59:54 PM,N,Y,3587,3555,0,1,0
238039,1.822724e+15,08/15/2018 02:08:22 PM,BROOKLYN,2431,FLATBUSH AVE & HILLEL PL,BROOKLYN,11210.0,70.0,45.0,314.0,...,08/15/2018 02:09:47 PM,08/15/2018 03:08:02 PM,08/15/2018 03:26:36 PM,N,Y,3580,3538,0,0,1
223451,1.823699e+15,08/24/2018 01:16:35 AM,QUEENS,9863,CLOVERDALE BLVD & KINGSBURY AVE,QUEENS,11364.0,111.0,23.0,411.0,...,08/24/2018 01:16:52 AM,08/24/2018 02:15:32 AM,08/24/2018 02:30:23 AM,N,Y,3537,3532,2,0,0
124919,1.829273e+15,10/19/2018 10:12:33 AM,QUEENS,7341,"BROADWAY, 200 FEET EAST OF 50 ST",QUEENS,11377.0,114.0,26.0,401.0,...,10/19/2018 10:13:19 AM,10/19/2018 11:11:32 AM,10/19/2018 11:19:19 AM,N,Y,3539,3516,2,0,0
3322044,1.304116e+15,02/10/2013 05:27:54 PM,BROOKLYN,1629,EAST 91 ST & RUTLAND RD,BROOKLYN,11212.0,67.0,41.0,317.0,...,02/10/2013 05:28:47 PM,02/10/2013 06:26:54 PM,02/10/2013 06:27:28 PM,N,Y,3540,3512,0,1,0
2668421,1.416174e+15,06/10/2014 12:06:34 PM,QUEENS,7446,31 DR & VERNON BLVD,QUEENS,11106.0,114.0,26.0,401.0,...,06/10/2014 12:07:41 PM,06/10/2014 01:05:47 PM,06/10/2014 02:28:24 PM,N,Y,3553,3503,0,0,1
164824,1.826933e+15,09/26/2018 11:23:55 AM,BROOKLYN,3335,AVENUE U & E 23 ST,BROOKLYN,11229.0,61.0,48.0,315.0,...,09/26/2018 11:24:38 AM,09/26/2018 12:22:25 PM,09/26/2018 12:23:29 PM,N,Y,3510,3500,2,0,0
2283784,1.505934e+15,02/28/2015 09:00:49 AM,BROOKLYN,3391,SHELL RD 200' S OF AVENUE X,BROOKLYN,11223.0,61.0,47.0,315.0,...,02/28/2015 09:02:19 AM,02/28/2015 10:00:18 AM,02/28/2015 04:04:36 PM,N,Y,3569,3490,1,2,1
765660,1.727632e+15,10/03/2017 08:50:51 PM,BRONX,3214,RHINELANDER AVE & WHITE PLAINS RD,BRONX,NaN,NaN,NaN,NaN,...,10/03/2017 08:51:26 PM,10/03/2017 09:49:25 PM,10/03/2017 09:50:04 PM,N,Y,3514,3479,1,0,0
1580357,1.613880e+15,05/17/2016 07:15:52 PM,RICHMOND / STATEN ISLAND,8039,FRONT ST 250' E/O EDGEWATER & BAY STS,RICHMOND / STATEN ISLAND,NaN,NaN,NaN,NaN,...,05/17/2016 07:17:42 PM,05/17/2016 08:15:23 PM,05/17/2016 10:13:15 PM,N,Y,3571,3461,0,0,4
2903229,1.335906e+15,12/25/2013 10:40:02 PM,BROOKLYN,564,FULTON & BRIDGE STS,BROOKLYN,11201.0,84.0,33.0,302.0,...,12/25/2013 10:40:29 PM,12/25/2013 11:37:46 PM,12/25/2013 11:48:39 PM,N,Y,3464,3453,0,1,0
223125,1.823646e+15,08/24/2018 09:00:22 AM,BRONX,4554,CITY ISLAND AVE & EARLY ST,BRONX,10464.0,45.0,13.0,210.0,...,08/24/2018 09:01:24 AM,08/24/2018 09:58:40 AM,08/24/2018 09:59:06 AM,N,Y,3498,3436,1,0,0
757285,1.728180e+15,10/08/2017 11:03:59 PM,BROOKLYN,8047,FLUSHING & WASHINGTON AVES-NAVAL SUPPORT,BROOKLYN,NaN,NaN,NaN,NaN,...,10/08/2017 11:05:19 PM,10/09/2017 12:02:23 AM,10/09/2017 01:39:08 AM,N,Y,3504,3434,0,0,3
2189091,1.512094e+15,04/30/2015 02:43:43 PM,QUEENS,9403,SANFORD AVE & HAIGHT ST,QUEENS,11355.0,109.0,20.0,407.0,...,04/30/2015 02:44:24 PM,04/30/2015 03:40:45 PM,04/30/2015 04:01:54 PM,N,Y,3422,3406,0,2,0
900094,1.719438e+15,07/13/2017 11:05:33 PM,BROOKLYN,3821,FLATBUSH AVE & BELT PKWY,BROOKLYN,NaN,NaN,NaN,NaN,...,07/13/2017 11:06:17 PM,07/14/2017 12:03:00 AM,07/14/2017 01:09:57 AM,N,Y,3447,3403,0,0,3
1964201,1.525635e+15,09/13/2015 08:13:12 PM,RICHMOND / STATEN ISLAND,3479,MANSION & MCKEE AVES,RICHMOND / STATEN ISLAND,NaN,NaN,NaN,NaN,...,09/13/2015 08:13:58 PM,09/13/2015 09:10:36 PM,09/13/2015 09:45:15 PM,N,Y,3444,3398,0,0,2
1122571,1.705618e+15,02/25/2017 02:05:02 PM,BROOKLYN,1798,GLENMORE & SHEPHERD AVES,BROOKLYN,11208.0,75.0,37.0,305.0,...,02/25/2017 02:06:54 PM,02/25/2017 03:01:58 PM,02/25/2017 03:14:01 PM,N,Y,3416,3397,1,0,0
186646,1.825637e+15,09/13/2018 09:39:19 PM,BROOKLYN,3688,EMMONS AVE & KNAPP ST,BROOKLYN,11235.0,61.0,46.0,315.0,...,09/13/2018 09:40:53 PM,09/13/2018 10:36:46 PM,09/13/2018 10:41:59 PM,N,Y,3447,3390,0,0,2
443211,1.810502e+15,04/15/2018 11:43:50 PM,BROOKLYN,155,METROPOLITAN AVE & GRAHAM AVE,BROOKLYN,11211.0,94.0,34.0,301.0,...,04/15/2018 11:44:33 PM,04/16/2018 12:40:23 AM,04/16/2018 12:57:11 AM,N,Y,3393,3387,2,0,0
1702680,1.605709e+15,02/26/2016 07:46:49 AM,MANHATTAN,865,BROADWAY & W 51 ST,MANHATTAN,10019.0,18.0,3.0,105.0,...,02/26/2016 07:48:10 AM,02/26/2016 08:43:19 AM,02/26/2016 09:24:14 AM,N,Y,3390,3386,2,0,0
1471843,1.620570e+15,07/23/2016 09:26:08 AM,MANHATTAN,7007,BMT N-R @ LEXINGTON AVE & E 59 ST,MANHATTAN,10065.0,22.0,6.0,164.0,...,07/23/2016 09:26:36 AM,07/23/2016 10:22:33 AM,07/23/2016 10:37:05 AM,N,Y,3385,3379,2,0,0
1247119,1.634330e+15,12/08/2016 02:45:16 PM,BROOKLYN,2987,AVENUE M & E 9 ST,BROOKLYN,11230.0,66.0,44.0,312.0,...,12/08/2016 02:45:49 PM,12/08/2016 03:41:39 PM,12/08/2016 03:50:02 PM,N,Y,3383,3377,2,0,0
1483800,1.619885e+15,07/16/2016 01:00:58 PM,MANHATTAN,8490,GEORGE WASHINGTON BRIDGE UPPER DECK,MANHATTAN,NaN,NaN,NaN,NaN,...,07/16/2016 01:02:06 PM,07/16/2016 01:57:44 PM,07/16/2016 01:59:46 PM,N,Y,3406,3367,1,0,0
269296,1.820910e+15,07/28/2018 09:54:23 PM,BROOKLYN,992,VANDERBILT AVE & ST MARKS AVE,BROOKLYN,11238.0,78.0,35.0,308.0,...,07/28/2018 09:55:49 PM,07/28/2018 10:51:17 PM,07/28/2018 11:00:15 PM,N,Y,3414,3347,1,0,0
3332870,1.303366e+15,02/02/2013 04:44:22 AM,QUEENS,6608,HIGHLAND AVE & AVA PL,QUEENS,11432.0,107.0,24.0,408.0,...,02/02/2013 04:44:59 AM,02/02/2013 05:40:16 AM,02/02/2013 05:49:56 AM,N,Y,3354,3346,2,0,0
2522333,1.426380e+15,09/20/2014 01:18:51 PM,RICHMOND / STATEN ISLAND,8039,FRONT ST 250' E/O EDGEWATER & BAY STS,RICHMOND / STATEN ISLAND,NaN,NaN,NaN,NaN,...,09/20/2014 01:20:40 PM,09/20/2014 02:15:22 PM,09/20/2014 03:02:25 PM,N,Y,3391,3343,0,0,4
250407,1.822009e+15,08/08/2018 02:13:46 PM,MANHATTAN,914,10 AVE & W 57 ST,MANHATTAN,10019.0,18.0,6.0,104.0,...,08/08/2018 02:14:07 PM,08/08/2018 03:09:33 PM,08/08/2018 03:20:08 PM,N,Y,3347,3342,2,0,0
773877,1.727109e+15,09/28/2017 08:52:27 PM,MANHATTAN,945,AMSTERDAM AVE & 61 ST,MANHATTAN,10023.0,20.0,6.0,107.0,...,09/28/2017 08:53:26 PM,09/28/2017 09:48:49 PM,09/28/2017 10:10:11 PM,N,Y,3382,3339,0,2,0
846692,1.722623e+15,08/14/2017 08:01:40 PM,BRONX,2262,TINTON AVE & 152 ST,BRONX,10455.0,40.0,17.0,201.0,...,08/14/2017 08:02:18 PM,08/14/2017 08:57:30 PM,08/14/2017 09:05:58 PM,N,Y,3350,3337,2,0,0
1130210,1.705112e+15,02/20/2017 11:01:23 AM,BROOKLYN,1222,PLAZA ST & BERKLEY PL,BROOKLYN,11217.0,78.0,39.0,306.0,...,02/20/2017 11:03:25 AM,02/20/2017 11:58:35 AM,02/20/2017 12:10:00 PM,N,Y,3432,3336,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3049836,1.324738e+15,09/04/2013 01:02:14 PM,BROOKLYN,3806,RICHARDS ST & HAMILTON AVE,BROOKLYN,11231.0,76.0,38.0,306.0,...,09/04/2013 01:02:23 PM,09/04/2013 01:02:24 PM,09/04/2013 01:19:38 PM,N,Y,10,1,3,2,1
2237571,1.508936e+15,03/30/2015 03:23:28 PM,BROOKLYN,3566,W 8 ST 400' N OF SURF AVE,BROOKLYN,NaN,NaN,NaN,NaN,...,03/30/2015 03:23:45 PM,03/30/2015 03:23:46 PM,03/30/2015 03:42:27 PM,N,Y,18,1,1,0,0
1352626,1.627709e+15,10/03/2016 02:44:30 PM,BROOKLYN,938,NOSTRAND AVE & MONROE ST,BROOKLYN,NaN,NaN,NaN,NaN,...,10/03/2016 02:44:43 PM,10/03/2016 02:44:44 PM,10/03/2016 03:10:46 PM,N,Y,14,1,1,0,0
3011891,1.327630e+15,10/03/2013 03:57:26 PM,BRONX,2972,E TREMONT AVE & VYSE AVE,BRONX,NaN,NaN,NaN,NaN,...,10/03/2013 03:57:52 PM,10/03/2013 03:57:53 PM,10/03/2013 05:49:00 PM,N,Y,27,1,1,0,0
336286,1.817110e+15,06/20/2018 04:05:21 PM,MANHATTAN,972,AMSTERDAM AVE & 65 ST,MANHATTAN,NaN,NaN,NaN,NaN,...,06/20/2018 04:05:26 PM,06/20/2018 04:05:27 PM,06/20/2018 04:21:56 PM,N,Y,6,1,1,0,0
975145,1.715124e+15,05/31/2017 09:23:08 AM,BROOKLYN,2448,GLENWOOD RD & BEDFORD AVE,BROOKLYN,11210.0,70.0,45.0,314.0,...,05/31/2017 09:24:48 AM,05/31/2017 09:24:04 AM,05/31/2017 09:33:14 AM,N,Y,56,1,3,2,1
117778,1.829626e+15,10/23/2018 02:20:26 PM,BROOKLYN,2584,12 AVE & 43 ST,BROOKLYN,NaN,NaN,NaN,NaN,...,10/23/2018 02:20:59 PM,10/23/2018 02:21:00 PM,10/23/2018 02:32:21 PM,N,Y,34,1,1,0,0
2983716,1.329805e+15,10/25/2013 07:32:34 PM,MANHATTAN,470,1 AVE & E 14 ST,MANHATTAN,10003.0,9.0,2.0,103.0,...,10/25/2013 07:33:16 PM,10/25/2013 07:33:17 PM,10/25/2013 07:48:24 PM,N,Y,43,1,2,2,1
1480741,1.620022e+15,07/18/2016 08:51:26 AM,BRONX,2156,CYPRESS AVE & 138 ST,BRONX,NaN,NaN,NaN,NaN,...,07/18/2016 08:51:35 AM,07/18/2016 08:51:36 AM,07/18/2016 09:23:18 AM,N,Y,10,1,1,0,0
776744,1.727026e+15,09/27/2017 08:52:53 AM,BRONX,2572,MORRIS AVE & E 167 ST,BRONX,NaN,NaN,NaN,NaN,...,09/27/2017 08:53:08 AM,09/27/2017 08:53:09 AM,09/27/2017 09:54:40 AM,N,Y,16,1,1,0,0
2146477,1.514745e+15,05/27/2015 01:08:26 PM,QUEENS,4525,14 RD & 120 ST,QUEENS,NaN,NaN,NaN,NaN,...,05/27/2015 01:08:36 PM,05/27/2015 01:08:37 PM,05/27/2015 01:09:48 PM,N,Y,11,1,1,0,0
2946793,1.332712e+15,11/23/2013 10:21:11 AM,MANHATTAN,1157,LEXINGTON AVE & 85 ST,MANHATTAN,NaN,NaN,NaN,NaN,...,11/23/2013 10:21:34 AM,11/23/2013 10:21:35 AM,11/23/2013 10:29:42 AM,N,Y,24,1,1,0,0
1500314,1.618816e+15,07/06/2016 05:43:18 PM,MANHATTAN,1584,HAMILTON PL & 139 ST,MANHATTAN,NaN,NaN,NaN,NaN,...,07/06/2016 05:44:01 PM,07/06/2016 05:44:02 PM,07/06/2016 06:15:14 PM,N,Y,44,1,1,0,0
1261677,1.633414e+15,11/29/2016 11:02:37 AM,MANHATTAN,1367,5 AVE & 114 ST,MANHATTAN,NaN,NaN,NaN,NaN,...,11/29/2016 11:02:42 AM,11/29/2016 11:02:43 AM,11/29/2016 11:04:55 AM,N,Y,6,1,0,1,0
2166891,1.513440e+11,05/14/2015 10:44:29 AM,BROOKLYN,3974,AVENUE R & OCEAN AVE,BROOKLYN,NaN,NaN,NaN,NaN,...,NaN,05/14/2015 10:48:40 AM,05/14/2015 11:04:04 AM,N,Y,251,0,0,1,0
2076446,1.518908e+15,07/08/2015 06:58:31 PM,MANHATTAN,761,8 AVE & W 39 ST,MANHATTAN,10018.0,14.0,3.0,104.0,...,07/08/2015 07:00:01 PM,07/08/2015 06:59:27 PM,07/08/2015 07:35:31 PM,N,Y,56,0,3,2,1
2363295,1.500908e+15,01/09/2015 05:09:35 PM,MANHATTAN,816,10 AVE & W 45 ST,MANHATTAN,10036.0,18.0,3.0,104.0,...,01/09/2015 05:15:55 PM,01/09/2015 05:15:31 PM,01/09/2015 05:26:07 PM,N,Y,356,0,3,2,2
2868834,1.401731e+15,01/17/2014 12:29:01 PM,BRONX,3121,JEROME & BURNSIDE AVES,BRONX,10453.0,46.0,14.0,205.0,...,01/17/2014 12:29:26 PM,01/17/2014 12:29:11 PM,01/17/2014 01:14:19 PM,N,Y,10,0,1,0,0
491403,1.807486e+15,03/15/2018 10:24:44 AM,MANHATTAN,8609,FDR DR - E 48 TO E 61 ST,MANHATTAN,10065.0,19.0,5.0,108.0,...,03/15/2018 10:25:21 AM,03/15/2018 10:25:08 AM,03/15/2018 11:25:12 AM,N,Y,24,0,3,4,1
3014327,1.327409e+15,10/01/2013 07:46:00 PM,MANHATTAN,904,1 AVE & E 56 ST,MANHATTAN,10022.0,17.0,5.0,106.0,...,10/01/2013 07:46:39 PM,10/01/2013 07:46:30 PM,10/01/2013 08:10:28 PM,N,Y,30,0,3,2,1
2813270,1.405802e+15,02/27/2014 12:59:33 AM,RICHMOND / STATEN ISLAND,210,VICTORY BLVD & PARK RD,RICHMOND / STATEN ISLAND,10301.0,120.0,49.0,501.0,...,02/27/2014 01:00:06 AM,02/27/2014 12:59:37 AM,02/27/2014 01:32:04 AM,N,Y,4,0,1,1,0
1624175,1.610936e+15,04/18/2016 02:02:51 PM,BRONX,3614,BARNES AVE & MAGENTA ST,BRONX,10467.0,47.0,12.0,212.0,...,04/18/2016 02:05:01 PM,04/18/2016 02:03:05 PM,04/18/2016 02:14:38 PM,N,Y,14,0,0,2,0
1533825,1.616822e+11,06/16/2016 03:13:53 AM,BRONX,2184,MORRIS AVE & 144 ST,BRONX,10451.0,40.0,8.0,201.0,...,06/16/2016 03:14:25 AM,06/16/2016 03:16:41 AM,06/16/2016 04:30:10 AM,N,Y,168,0,1,0,0
583745,1.801616e+15,01/16/2018 03:41:22 PM,BROOKLYN,1639,SUTTER AVE & UNION ST,BROOKLYN,11212.0,73.0,41.0,316.0,...,01/16/2018 03:41:49 PM,01/16/2018 03:41:39 PM,01/16/2018 04:20:57 PM,N,Y,17,0,3,2,2
362862,1.815505e+15,06/04/2018 08:02:12 PM,MANHATTAN,515,WAVERLY PL & CHARLES ST,MANHATTAN,10014.0,6.0,3.0,102.0,...,06/04/2018 08:02:49 PM,06/04/2018 08:02:49 PM,06/04/2018 08:35:39 PM,N,Y,37,0,0,0,1
1076399,1.708714e+15,03/28/2017 04:13:06 AM,MANHATTAN,1406,PARK AVE & E 118 ST,MANHATTAN,10035.0,25.0,9.0,111.0,...,03/28/2017 04:15:01 AM,03/28/2017 04:20:10 AM,03/28/2017 05:07:44 AM,N,Y,424,0,0,1,0
1719638,1.604709e+15,02/16/2016 02:45:48 AM,BROOKLYN,882,STUYVESANT & PUTNAM AVES,BROOKLYN,11221.0,81.0,36.0,303.0,...,02/16/2016 02:46:22 AM,02/16/2016 02:46:12 AM,02/16/2016 03:31:42 AM,N,Y,24,0,4,3,1
2114584,1.516645e+15,06/15/2015 02:14:52 PM,QUEENS,4466,38 AVE & UNION ST,QUEENS,11354.0,109.0,20.0,407.0,...,06/15/2015 03:28:41 PM,06/15/2015 03:07:33 PM,06/15/2015 05:12:11 PM,N,Y,3161,0,1,0,1
2084357,1.518489e+15,07/03/2015 11:52:04 PM,BRONX,8897,CROSS BX XWAY DEEGAN XWAY TO JEROME AVE,BRONX,10452.0,46.0,14.0,205.0,...,07/03/2015 11:55:30 PM,07/03/2015 11:55:14 PM,07/04/2015 12:55:22 AM,N,Y,190,0,3,2,1
2811459,1.405907e+15,02/28/2014 12:55:14 PM,MANHATTAN,667,2 AVE & E 29 ST,MANHATTAN,10016.0,13.0,2.0,106.0,...,02/28/2014 12:56:02 PM,02/28/2014 12:56:02 PM,02/28/2014 01:15:05 PM,N,Y,48,0,3,2,1

130.0
480.0

(2757412, 29)